spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl21pdb1
    driver-class-name: oracle.jdbc.OracleDriver
    username: C##mbatch_user
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate # hoặc create-drop nếu muốn drop table khi shutdown
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

jwt:
  secret:
    key: Z3VqQ2VydFNlY3JldEtleU15U3RyaW5nMTIzNDU2Nzg=
  expiration:
    ms: 86400000
