CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role_id NUMBER,
    manager_id NUMBER
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles(id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_manager
        FOREIGN KEY (manager_id) REFERENCES users(id);

CREATE TABLE expense_requests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    amount NUMBER(12,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    employee_id NUMBER,
    receipt_image_url VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE expense_requests
    ADD CONSTRAINT fk_expense_employee
        FOREIGN KEY (employee_id) REFERENCES users(id);

CREATE TABLE request_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER,
    actor_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    comment VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE request_history
    ADD CONSTRAINT fk_history_request
        FOREIGN KEY (request_id) REFERENCES expense_requests(id);

ALTER TABLE request_history
    ADD CONSTRAINT fk_history_actor
        FOREIGN KEY (actor_id) REFERENCES users(id);
